### ISSUE TITLE
リンク切れ？

### ISSUE THREAD

**Issue by shimesaba-type0** [virtualtech/openstack-kilo-docs#1]
PDFの35枚目、章でいうと、5-5 Apache Webサーバーの設定のところですが、

```
controller# curl http://git.openstack.org/cgit/openstack/keystone/plain/httpd/key
stone.py?h=stable/kilo \
| tee /var/www/cgi-bin/keystone/main /var/www/cgi-bin/keystone/admin
```

このリンクが既になくなっているように思われます。
代わりのリンクが有りましたら教えて頂けますでしょうか。

**Comment by ytooyama** [comment]
KiloはEOLのため、OpenStack公式のGitから削除されたと思われます。対応方法は基本的にはありません。
https://bugs.launchpad.net/keystone/+bug/1596415

**Comment by ytooyama** [comment]
次のようにURLが変わっているようです。
http://git.openstack.org/cgit/openstack/keystone/plain/httpd/keystone.py?h=kilo-eol

**Comment by shimesaba-type0** [comment]
コメントありがとうございます。
ちなみに、私は別の方法で試したところ、出来ましたので共有させて頂きます。
1. https://tarballs.openstack.org/keystone/keystone-2015.1.4.tar.gz　をダウンロード
2. keystone-2015.1.4.tar.gzを展開
3. keystone-2015.1.4/httpd/keystone.py の中身をコピー
4. /var/www/cgi-bin/keystone/main 及び /var/www/cgi-bin/keystone/admin に貼り付け
5. apache2のリロード、その後再起動

使う機会はあまり無いでしょうが備忘録的な位置づけで残させて頂きます。
